### PR TITLE
Implement logic to show all comments to voting members, only self-authored comments to non-voting members

### PR DESCRIPTION
**Pull request by anaulin**
### What does this code do, and why?

Implements https://github.com/doubleunion/arooo/issues/486:
* all application comments are now visible to all voting members
* a non-voting member can only see their own comments on an application
* there is now an explanatory text about comment visibility

### How is this code tested?

Specs! And also local manual testing.

### Are any database migrations required by this change?

Nope.

### Screenshots (before/after)

**Before**:
Screen Shot 2021-01-01 at 9 45 35 PM

**After**:
Screen Shot 2021-01-01 at 9 50 00 PM

### Are there any configuration or environment changes needed?

No, ma'am.

### CODE REVIEW

**Comment by anaulin** [comment]
@brittag here is my stab at this. Let me know what you think about the wording of the explanation bits (visible in screenshots).

**Comment by brittag** [comment]
@anaulin Thank you! I tried making the language more direct and aligned it with the current Voting Policy doc (also clarified the doc). I don't know how to make a sample application locally, so I don't know how to preview what this looks like - so I welcome review!

**Comment by anaulin** [comment]
@brittag here is a screenshot (looks fine IMO)
Screen Shot 2021-01-02 at 8 23 01 PM

**Comment by brittag** [comment]
@anaulin I think that's the same screenshot as before instead of a new screenshot? But yeah, as long as it looks good to you, that's enough!

**Comment by anaulin** [comment]
@brittag lol, sorry 🤦

**Pull request merged**
