### PR TITLE
Update stripe gem

### PR DESCRIPTION
**Pull request by compwron**
Changelog: https://github.com/stripe/stripe-ruby/blob/master/CHANGELOG.md
As far as I can tell there is no breaking change in major version 2->3
I ran: `bundle update stripe stripe-ruby-mock stripe_event`

> 3.0.0 - 2017-06-27
> #pay on invoice now takes params as well as opts

### CODE REVIEW

**Comment by compwron** [comment]
Since billing happens on the 8th, we should merge and test this either well before then, or after... not during :) 
Screen Shot 2019-05-30 at 10 56 31 PM

**Comment by Imperiopolis** [comment]
> Since billing happens on the 8th, we should merge and test this either well before then, or after... not during :)

Note, billing happens on a rolling basis, it's not quite as simple as this – stripe batches people into a few groups through the month, I believe based on the time of month they signed up for dues. I think you should be able to login to stripe and look at what's scheduled and when things come through. 

I'm not sure how much our app actually interacts with stripe beyond setting up the initial recurring payment, also, so problems with this might not crop up until new members start signing up for dues or someone tries to adjust their dues amount.

All that said, I trust your judgement on this – I'd generally be in favor of getting it in place before we start accepting applications.

**Comment by compwron** [comment]
I'm going to merge and deploy this and then cancel and re-start my own dues to check that it works :)

**Comment by compwron** [comment]
I tested this and it works

**Comment by Imperiopolis-Signal** [comment]
🎉

**Pull request merged**
