### PR TITLE
Add basic admin UI to create, edit and generate new door codes

### PR DESCRIPTION
**Pull request by anaulin**
As part of the work in https://github.com/doubleunion/arooo/issues/594 to support the new door code workflows, this PR adds some UIs for admins to administer door codes, including:
* see all existing door codes and their statuses
* edit an existing door code (this includes assigning a door code to a user)
* manually enter a new door code in the database
* autogenerate 10 new unique door codes

Screenshots of the new UIs:

Screen Shot 2021-12-10 at 5 59 01 PM

Screen Shot 2021-12-10 at 5 59 11 PM

Screen Shot 2021-12-10 at 5 59 28 PM

### CODE REVIEW

**Comment by brittag** [comment]
I haven't tried this locally yet, but the screenshots look pretty good to me! Would we give the formerly_assigned_in_lock status to codes that we previously created in the lock (and presumably assigned) and have deleted from the lock?

**Comment by anaulin** [comment]
Yes, the intent for the "formerly_assigned..." statuses is to support the workflow where we un-assign a code from a member, but we need to mark somehow that someone needs to remove it from the lock. Once it is removed from the lock, we still want to keep it in the database to avoid reuse.

We can refine all of this as we figure out the precise workflows.

**Comment by anaulin** [comment]
I'm going to merge this, so that I can deploy it and we can start trying to feel it out and properly test it.

**Comment by anaulin** [comment]
Happy to address any comments or issues in follow-up PRs, if anyone sees something.

**Pull request merged**
